code/admins/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import TemplateView
from . import views

app_name='admins'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/list/', views.MenuList, name='MenuList'),
    path('menu/list/api', views.MenuListAPI, name='MenuListAPI'),
    path('menu/add/', views.MenuAdd, name='MenuAdd'),
    re_path(r'^menu/detail/(?P<id>\d+)/$', views.MenuDetail, name='MenuDetail'),
    re_path(r'^menu/update/(?P<id>\d+)/$', views.MenuUpdate, name='MenuUpdate'),
    re_path(r'^menu/delete/(?P<id>\d+)/$', views.MenuDelete, name='MenuDelete'),
    path('user/list/', views.UserList, name='UserList'),
    path('user/list/api', views.UserListAPI, name='UserListAPI'),
    path('user/add/', views.UserAdd, name='UserAdd'),
    path('user/set/', views.UserSet, name='UserSet'),
    re_path(r'^user/detail/(?P<id>\d+)/$', views.UserDetail, name='UserDetail'),
    re_path(r'^user/profile/(?P<id>\d+)/$', views.UserProfile, name='UserProfile'),
    re_path(r'^user/update/(?P<id>\d+)/$', views.UserUpdate, name='UserUpdate'),
    re_path(r'^user/resetpass/(?P<id>\d+)/$', views.ResetPass, name='ResetPass'),
    re_path(r'^user/delete/(?P<id>\d+)/$', views.UserDelete, name='UserDelete'),
    re_path(r'^user/changepass/(?P<id>\d+)/$', views.ChangePass, name='ChangePass'),
    path('role/list/', views.RoleList, name='RoleList'),
    path('role/add/', views.RoleAdd, name='RoleAdd'),
    re_path(r'^role/update/(?P<id>\d+)/$', views.RoleUpdate, name='RoleUpdate'),
    re_path(r'^role/delete/(?P<id>\d+)/$', views.RoleDelete, name='RoleDelete'),
    path('perm/list/', views.PermList, name='PermList'),
    path('perm/update/', views.PermUpdate, name='PermUpdate'),
    path('service/list/', views.ServiceList, name='ServiceList'),
    re_path(r'^service/update/(?P<id>\d+)/$', views.ServiceUpdate, name='ServiceUpdate'),
]

code/cmdb/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name='cmdb'
urlpatterns = [
    path('host/create_or_update', views.CreateOrUpdateHostAPI, name='CreateOrUpdateHost'),
    path('host/index', views.HostIndex, name='HostIndex'),
    path('host/list', views.HostList, name='HostList'),
    path('host/select', views.HostSelect, name='HostSelect'),
    path('host/list/api', views.HostListAPI, name='HostListAPI'),
    path('host/add', views.HostAdd, name='HostAdd'),
    path('host/model', views.HostModel, name='HostModel'),
    path('host/addprop', views.HostAddProp, name='HostAddProp'),
    path('host/search', views.HostSearch, name='HostSearch'),
    path('host/hostupdatebatch', views.HostUpdateBatch, name='HostUpdateBatch'),
    path('host/hostexport', views.HostExport, name='HostExport'),
    path('host/hostimport', views.HostImport, name='HostImport'),
    re_path(r'^host/detail/(?P<id>\d+)/$', views.HostDetail, name='HostDetail'),
    re_path(r'^host/update/(?P<id>\d+)/$', views.HostUpdate, name='HostUpdate'),
    re_path(r'^host/delete/(?P<id>\d+)/$', views.HostDelete, name='HostDelete'),
    re_path(r'^host/updateprop/(?P<id>\d+)/$', views.HostUpdateProp, name='HostUpdateProp'),
    re_path(r'^host/delprop/(?P<id>\d+)/$', views.HostDelProp, name='HostDelProp'),
]

code/admins/templates/menu/add.html
{% load staticfiles %}
<!DOCTYPE html>
<html style="padding-left: 10px; padding-right: 10px">
<head>
  <meta charset="utf-8">
  <title>admins-MenuAdd</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}"  media="all">
  <!-- 注意：如果你直接复制所有代码到本地，上述css路径需要改成你本地的 -->
</head>
<body>
              
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
  <legend>添加模块</legend>
</fieldset>
 
<form class="layui-form" action="">{% csrf_token %}
  <div class="layui-form-item">
    <label class="layui-form-label">模块名称 <span style="color: #FF5722">*</span></label>
    <div class="layui-input-block">
      <input type="text" name="name" lay-verify="required" autocomplete="off" placeholder="请输入名称" class="layui-input">
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">模块ID <span style="color: #FF5722">*</span></label>
    <div class="layui-input-block">
      <input type="text" name="code" lay-verify="required" placeholder="请输入" autocomplete="off" class="layui-input">
    </div>
  </div>

  <div class="layui-form-item">
    <label class="layui-form-label">URL配置 <span style="color: #FF5722">*</span></label>
    <div class="layui-input-block">
      <input type="text" name="url" lay-verify="required" placeholder="请输入" autocomplete="off" class="layui-input">
    </div>
  </div>
  
<!--   <div class="layui-form-item">
    <label class="layui-form-label">开关-默认关</label>
    <div class="layui-input-block">
      <input type="checkbox" name="close" lay-skin="switch" lay-text="ON|OFF">
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">开关-默认开</label>
    <div class="layui-input-block">
      <input type="checkbox" checked="" name="open" lay-skin="switch" lay-filter="switchTest" lay-text="ON|OFF">
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">单选框</label>
    <div class="layui-input-block">
      <input type="radio" name="sex" value="男" title="男" checked="">
      <input type="radio" name="sex" value="女" title="女">
      <input type="radio" name="sex" value="禁" title="禁用" disabled="">
    </div>
  </div> -->
  <div class="layui-form-item layui-form-text">
    <label class="layui-form-label">备注说明 </label>
    <div class="layui-input-block">
      <textarea name='comment' placeholder="请输入内容" class="layui-textarea"></textarea>
    </div>
  </div>

  <div class="layui-form-item">
    <div class="layui-input-block">
      <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="demo1">立即提交</button>
      <a class="layui-btn layui-btn-sm layui-btn-primary" onClick="javascript :history.back(-1);">取消</a>
    </div>
  </div>
</form>
          
<script src="{% static 'layui/layui.all.js' %}" charset="utf-8"></script>
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
<script>
  var form = layui.form;
  form.on('submit(demo1)', function(data){
      //console.log(data.elem) //被执行事件的元素DOM对象，一般为button对象
      //console.log(data.form) //被执行提交的form对象，一般在存在form标签时才会返回
      // console.log(data.field) //当前容器的全部表单字段，名值对形式：{name: value}
      var $ = layui.$;

      // get list of roles
      // data.field['roles'] = $("input[name='roles']:checkbox:checked").map(function(){return $(this).val();}).get()

      var index = layer.load(1);
      $.post("{% url 'admins:MenuAdd' %}", data.field, function(res){
          if (res.code){
              layer.msg(res.msg, {icon: 1});
              setTimeout("window.location.href= \"{% url 'admins:MenuList' %}\"", 2000);
          }
          else {
              layer.alert('错误信息:'+ res.msg);
          }
          layer.close(index);
      });
      return false; //阻止表单跳转。如果需要表单跳转，去掉这段即可。
  });
</script>

</body>
</html>

code/admins/templates/menu/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html style="padding-left: 10px; padding-right: 10px">
<head>
  <meta charset="utf-8">
  <title>admins-MenuDetail</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}"  media="all">
  <!-- 注意：如果你直接复制所有代码到本地，上述css路径需要改成你本地的 -->
</head>
<body>
              
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
  <legend>模块管理</legend>
</fieldset>
<form class="layui-form" action="">
  <div class="layui-form-item">
    <label class="layui-form-label">模块名称 <span style="color: #FF5722">*</span></label>
    <div class="layui-input-block">
      <input type="text" name="name" lay-verify="required" autocomplete="off" placeholder="请输入名称" class="layui-input" value="{{menu.name}}" disabled>
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">模块ID <span style="color: #FF5722">*</span></label>
    <div class="layui-input-block">
      <input type="text" name="code" lay-verify="required" placeholder="请输入" autocomplete="off" class="layui-input" value="{{menu.code}}" disabled>
    </div>
  </div>

  <div class="layui-form-item">
    <label class="layui-form-label">URL配置 <span style="color: #FF5722">*</span></label>
    <div class="layui-input-block">
      <input type="text" name="url" lay-verify="required" placeholder="请输入" autocomplete="off" class="layui-input" value="{{menu.url}}" disabled>
    </div>
  </div>
  
  <div class="layui-form-item layui-form-text">
    <label class="layui-form-label">备注说明 </label>
    <div class="layui-input-block">
      <textarea name='comment' placeholder="请输入内容" class="layui-textarea" disabled>{{ menu.comment }}</textarea>
    </div>
  </div>

  <div class="layui-form-item">
    <div class="layui-input-block">
      <a href="{% url 'admins:MenuUpdate' menu.id %}" class="layui-btn layui-btn-sm">编辑</a>
      <a class="layui-btn layui-btn-sm layui-btn-primary" onClick="javascript :history.back(-1);">返回</a>
    </div>
  </div>
</form>
          
<script src="{% static 'layui/layui.all.js' %}" charset="utf-8"></script>
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->

</body>
</html>

code/admins/templates/menu/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html style="padding-left: 10px; padding-right: 10px; margin-top: 10px;">
<head>
  <meta charset="utf-8">
  <title>layui</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}"  media="all">
</head>
<body>

<a href="{% url 'admins:MenuAdd' %}"><button class="layui-btn">添加模块</button></a>

<table class="layui-hide" id="demo" lay-filter="demo"></table>

<script src="{% static 'layui/layui.all.js' %}" charset="utf-8"></script>
<script type="text/html" id="barDemo">
    <a class="layui-btn layui-btn-xs" lay-event="detail">查看</a>
    <a class="layui-btn layui-btn-xs" lay-event="update">编辑</a>
    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
</script>

<script>
    var table = layui.table;
    var $ = layui.$;
    var tableIns = table.render({
        elem: '#demo'
        ,url: '/admins/menu/list/api' //数据接口
        ,cols: [[
        {field: 'name', title: '菜单名称', width:150, fixed: true}
        ,{field: 'code', title: '菜单ID'}
        ,{field: 'url', title: 'URL'} 
        ,{field: 'comment', title: '备注说明'}
        ,{title: '操作', fixed: 'right', width:150, align:'center', toolbar: '#barDemo'}
        ]]
        ,page: true
        ,limits: [10,50,100,1000]
    });

    //监听工具条
    table.on('tool(demo)', function(obj){
        var data = obj.data;
        if(obj.event === 'del'){
            layer.confirm('确定删除？', function(index){
                $.get('/admins/menu/delete/' + data.id, function(res){
                    if (res.code) {
                        obj.del();
                        layer.msg(res.msg, {icon: 1});
                    }
                    else {
                        layer.alert('错误信息:'+ res.msg);
                    }
                });
                layer.close(index);
            });
        } else if(obj.event === 'update'){
            window.location.href = '/admins/menu/update/' + data.id;
        } else if(obj.event === 'detail') {
            window.location.href = '/admins/menu/detail/' + data.id;
        }
    });
</script>
</body>
</html>

code/admins/templates/menu/update.html
{% load staticfiles %}
<!DOCTYPE html>
<html style="padding-left: 10px; padding-right: 10px">
<head>
  <meta charset="utf-8">
  <title>admins-MenuAdd</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}"  media="all">
  <!-- 注意：如果你直接复制所有代码到本地，上述css路径需要改成你本地的 -->
</head>
<body>
              
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
  <legend>更新模块</legend>
</fieldset>
 
<form class="layui-form" action="">{% csrf_token %}
  <div class="layui-form-item">
    <label class="layui-form-label">模块名称 <span style="color: #FF5722">*</span></label>
    <div class="layui-input-block">
      <input type="text" name="name" lay-verify="required" autocomplete="off" placeholder="请输入名称" class="layui-input" value="{{menu.name}}">
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">模块ID <span style="color: #FF5722">*</span></label>
    <div class="layui-input-block">
      <input type="text" name="code" lay-verify="required" placeholder="请输入" autocomplete="off" class="layui-input" value="{{menu.code}}">
    </div>
  </div>

  <div class="layui-form-item">
    <label class="layui-form-label">URL配置 <span style="color: #FF5722">*</span></label>
    <div class="layui-input-block">
      <input type="text" name="url" lay-verify="required" placeholder="请输入" autocomplete="off" class="layui-input" value="{{menu.url}}">
    </div>
  </div>
  <div class="layui-form-item layui-form-text">
    <label class="layui-form-label">备注说明 </label>
    <div class="layui-input-block">
      <textarea name='comment' placeholder="请输入内容" class="layui-textarea">{{menu.comment}}</textarea>
    </div>
  </div>

  <div class="layui-form-item">
    <div class="layui-input-block">
      <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="demo1">提交更新</button>
      <a class="layui-btn layui-btn-sm layui-btn-primary" onClick="javascript :history.back(-1);">取消</a>
    </div>
  </div>
</form>
          
<script src="{% static 'layui/layui.all.js' %}" charset="utf-8"></script>
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
<script>
  var form = layui.form;
  form.on('submit(demo1)', function(data){
      var $ = layui.$;
      var index = layer.load(1);
      $.post("{% url 'admins:MenuUpdate' menu.id %}", data.field, function(res){
          if (res.code){
              layer.msg(res.msg, {icon: 1});
              setTimeout("window.location.href= \"{% url 'admins:MenuList' %}\"", 2000);
          }
          else {
              layer.alert('错误信息:'+ res.msg);
          }
          layer.close(index);
      });
      return false; //阻止表单跳转。如果需要表单跳转，去掉这段即可。
  });
</script>

</body>
</html>