code/admins/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import TemplateView
from . import views

app_name='admins'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/list/', views.MenuList, name='MenuList'),
    path('menu/list/api', views.MenuListAPI, name='MenuListAPI'),
    path('menu/add/', views.MenuAdd, name='MenuAdd'),
    re_path(r'^menu/detail/(?P<id>\d+)/$', views.MenuDetail, name='MenuDetail'),
    re_path(r'^menu/update/(?P<id>\d+)/$', views.MenuUpdate, name='MenuUpdate'),
    re_path(r'^menu/delete/(?P<id>\d+)/$', views.MenuDelete, name='MenuDelete'),
    path('user/list/', views.UserList, name='UserList'),
    path('user/list/api', views.UserListAPI, name='UserListAPI'),
    path('user/add/', views.UserAdd, name='UserAdd'),
    path('user/set/', views.UserSet, name='UserSet'),
    re_path(r'^user/detail/(?P<id>\d+)/$', views.UserDetail, name='UserDetail'),
    re_path(r'^user/profile/(?P<id>\d+)/$', views.UserProfile, name='UserProfile'),
    re_path(r'^user/update/(?P<id>\d+)/$', views.UserUpdate, name='UserUpdate'),
    re_path(r'^user/resetpass/(?P<id>\d+)/$', views.ResetPass, name='ResetPass'),
    re_path(r'^user/delete/(?P<id>\d+)/$', views.UserDelete, name='UserDelete'),
    re_path(r'^user/changepass/(?P<id>\d+)/$', views.ChangePass, name='ChangePass'),
    path('role/list/', views.RoleList, name='RoleList'),
    path('role/add/', views.RoleAdd, name='RoleAdd'),
    re_path(r'^role/update/(?P<id>\d+)/$', views.RoleUpdate, name='RoleUpdate'),
    re_path(r'^role/delete/(?P<id>\d+)/$', views.RoleDelete, name='RoleDelete'),
    path('perm/list/', views.PermList, name='PermList'),
    path('perm/update/', views.PermUpdate, name='PermUpdate'),
    path('service/list/', views.ServiceList, name='ServiceList'),
    re_path(r'^service/update/(?P<id>\d+)/$', views.ServiceUpdate, name='ServiceUpdate'),
]

code/cmdb/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name='cmdb'
urlpatterns = [
    path('host/create_or_update', views.CreateOrUpdateHostAPI, name='CreateOrUpdateHost'),
    path('host/index', views.HostIndex, name='HostIndex'),
    path('host/list', views.HostList, name='HostList'),
    path('host/select', views.HostSelect, name='HostSelect'),
    path('host/list/api', views.HostListAPI, name='HostListAPI'),
    path('host/add', views.HostAdd, name='HostAdd'),
    path('host/model', views.HostModel, name='HostModel'),
    path('host/addprop', views.HostAddProp, name='HostAddProp'),
    path('host/search', views.HostSearch, name='HostSearch'),
    path('host/hostupdatebatch', views.HostUpdateBatch, name='HostUpdateBatch'),
    path('host/hostexport', views.HostExport, name='HostExport'),
    path('host/hostimport', views.HostImport, name='HostImport'),
    re_path(r'^host/detail/(?P<id>\d+)/$', views.HostDetail, name='HostDetail'),
    re_path(r'^host/update/(?P<id>\d+)/$', views.HostUpdate, name='HostUpdate'),
    re_path(r'^host/delete/(?P<id>\d+)/$', views.HostDelete, name='HostDelete'),
    re_path(r'^host/updateprop/(?P<id>\d+)/$', views.HostUpdateProp, name='HostUpdateProp'),
    re_path(r'^host/delprop/(?P<id>\d+)/$', views.HostDelProp, name='HostDelProp'),
]

code/dataPlus/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.base, name='base'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('cmdb/', include('cmdb.urls', namespace='cmdb')),
    re_path(r'^django-rq/', include('django_rq.urls')),
]

code/jobs/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name='jobs'
urlpatterns = [
    path('index', views.JobIndex, name='JobIndex'),
    path('cmd', views.JobCmd, name='JobCmd'),
    path('scripts/list', views.ScriptIndex, name='ScriptIndex'),
    path('scripts/list/api', views.ScriptListAPI, name='ScriptListAPI'),
    path('file/upload', views.UploadFile, name='UploadFile'),
	re_path(r'file/delete/(?P<id>\d+)/$', views.DeleteFile, name='DeleteFile'),
	re_path(r'file/view/(?P<id>\d+)/$', views.ViewFile, name='ViewFile'),
	re_path(r'script/run/(?P<id>\d+)/$', views.ScriptRun, name='ScriptRun'),
	path('files/list', views.FileIndex, name='FileIndex'),
	path('files/list/api', views.FileListAPI, name='FileListAPI'),
	re_path(r'file/push/(?P<id>\d+)/$', views.FilePush, name='FilePush'),
	path('states/list', views.StateIndex, name='StateIndex'),
	path('states/list/api', views.StateListAPI, name='StateListAPI'),
	re_path(r'state/deploy/(?P<id>\d+)/$', views.StateDeploy, name='StateDeploy'),
	path('cron/list', views.CronIndex, name='CronIndex'),
	path('cron/list/api', views.CronListAPI, name='CronListAPI'),
	path('cron/add', views.CronAdd, name='CronAdd'),
	re_path(r'cron/delete/(?P<id>.+)/$', views.CronDelete, name='CronDelete'),
	path('result/list', views.JobList, name='JobList'),
	path('result/list/api', views.JobListAPI, name='JobListAPI'),
	re_path(r'result/detail/(?P<jid>.+)/$', views.JobResult, name='JobResult'),
]

code/templates/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>{% block title %} DataPlus {% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
  <link href="{% static 'pics/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
  <div class="layui-header" id="layui-header">
    <div class="layui-logo" style="font-size: 25px">
      <a href="/" style="color: #f8fcfb">Data Plus</a>
    </div>
    <!-- 头部区域（可配合layui已有的水平导航） -->
    <ul class="layui-nav layui-layout-left">
      <li class="layui-nav-item"><a href="{% url 'dashboard:index' %}" target="myiframe">Dashboard</a></li>
      <li class="layui-nav-item"><a href="{% url 'cmdb:HostIndex' %}" target="myiframe">主机管理</a></li>
      <li class="layui-nav-item"><a href="{% url 'jobs:JobIndex' %}" target="myiframe">作业平台</a></li>
      <li class="layui-nav-item">
        <a href="javascript:;">更多模块</a>
        <dl class="layui-nav-child">
          {% for menu in menus  %}
            <dd><a href="{{ menu.url }}" target="myiframe">{{ menu.name }}</a></dd>
          {% endfor %}
        </dl>
      </li>
    </ul>
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item">
        <a href="javascript:;">
          <img src="{% static 'pics/user.jpg' %}" class="layui-nav-img">
          {{request.user.username}}
        </a>
        <dl class="layui-nav-child">
          <dd><a href="{% url 'admins:UserSet' %}" target="myiframe">账户设置</a></dd>
        </dl>
      </li>
      <li class="layui-nav-item"><a href="{% url 'logout' %}">注销</a></li>
    </ul>
  </div>
  
  <div class="layui-body" style="left: 0px" id="body">
     <iframe id="myiframe" name='myiframe' scrolling="yes" onload="changeFrameHeight()" frameborder="0" width="100%" src="{% url 'dashboard:index' %}"></iframe>
  </div>

  <div id="layui-footer" class="layui-footer footer" style="text-align: center;left: 0px; color: #393D49">
      ©2017
      <a href="http://www.jinmuinfo.com">上海锦木信息有限公司</a>
  </div>

</div>

<script src="{% static 'layui/layui.all.js' %}"></script>
<script type="text/javascript">
    function changeFrameHeight(){
        var ifm = document.getElementById("myiframe");
        var header = document.getElementById("layui-header").offsetHeight
        var footer = document.getElementById("layui-footer").offsetHeight
        // console.log(body, header, footer, document.documentElement.clientHeight);
        ifm.height = document.documentElement.clientHeight-header-footer-3;
      }

    window.onresize=function(){  
       changeFrameHeight();  
    } 
</script>
<script>
//JavaScript代码区域
layui.use('element', function(){
  var element = layui.element;
  
});
</script>
</body>
</html>