code/cmdb/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name='cmdb'
urlpatterns = [
    path('host/create_or_update', views.CreateOrUpdateHostAPI, name='CreateOrUpdateHost'),
    path('host/index', views.HostIndex, name='HostIndex'),
    path('host/list', views.HostList, name='HostList'),
    path('host/select', views.HostSelect, name='HostSelect'),
    path('host/list/api', views.HostListAPI, name='HostListAPI'),
    path('host/add', views.HostAdd, name='HostAdd'),
    path('host/model', views.HostModel, name='HostModel'),
    path('host/addprop', views.HostAddProp, name='HostAddProp'),
    path('host/search', views.HostSearch, name='HostSearch'),
    path('host/hostupdatebatch', views.HostUpdateBatch, name='HostUpdateBatch'),
    path('host/hostexport', views.HostExport, name='HostExport'),
    path('host/hostimport', views.HostImport, name='HostImport'),
    re_path(r'^host/detail/(?P<id>\d+)/$', views.HostDetail, name='HostDetail'),
    re_path(r'^host/update/(?P<id>\d+)/$', views.HostUpdate, name='HostUpdate'),
    re_path(r'^host/delete/(?P<id>\d+)/$', views.HostDelete, name='HostDelete'),
    re_path(r'^host/updateprop/(?P<id>\d+)/$', views.HostUpdateProp, name='HostUpdateProp'),
    re_path(r'^host/delprop/(?P<id>\d+)/$', views.HostDelProp, name='HostDelProp'),
]

code/jobs/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name='jobs'
urlpatterns = [
    path('index', views.JobIndex, name='JobIndex'),
    path('cmd', views.JobCmd, name='JobCmd'),
    path('scripts/list', views.ScriptIndex, name='ScriptIndex'),
    path('scripts/list/api', views.ScriptListAPI, name='ScriptListAPI'),
    path('file/upload', views.UploadFile, name='UploadFile'),
	re_path(r'file/delete/(?P<id>\d+)/$', views.DeleteFile, name='DeleteFile'),
	re_path(r'file/view/(?P<id>\d+)/$', views.ViewFile, name='ViewFile'),
	re_path(r'script/run/(?P<id>\d+)/$', views.ScriptRun, name='ScriptRun'),
	path('files/list', views.FileIndex, name='FileIndex'),
	path('files/list/api', views.FileListAPI, name='FileListAPI'),
	re_path(r'file/push/(?P<id>\d+)/$', views.FilePush, name='FilePush'),
	path('states/list', views.StateIndex, name='StateIndex'),
	path('states/list/api', views.StateListAPI, name='StateListAPI'),
	re_path(r'state/deploy/(?P<id>\d+)/$', views.StateDeploy, name='StateDeploy'),
	path('cron/list', views.CronIndex, name='CronIndex'),
	path('cron/list/api', views.CronListAPI, name='CronListAPI'),
	path('cron/add', views.CronAdd, name='CronAdd'),
	re_path(r'cron/delete/(?P<id>.+)/$', views.CronDelete, name='CronDelete'),
	path('result/list', views.JobList, name='JobList'),
	path('result/list/api', views.JobListAPI, name='JobListAPI'),
	re_path(r'result/detail/(?P<jid>.+)/$', views.JobResult, name='JobResult'),
]

code/jobs/models.py
from django.db import models

# Create your models here.

class File(models.Model):
    FILE_TYPE_CHOICE = (("script", "脚本"), ("state", "模块"), ("other", "其他"))
    code               = models.CharField(max_length=100)
    name               = models.CharField(max_length=100)
    file_type          = models.CharField(max_length=100, default="other")
    created_by         = models.CharField(max_length=80,blank=True,null=True)
    comment            = models.CharField(max_length=200,blank=True,null=True)
    create_time        = models.DateTimeField(auto_now_add=True)
    update_time        = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'upload_file'

    def __str__(self):
        return self.name

code/jobs/views.py
from django.shortcuts import render
from .utils import Cmd, upload_file, run_script, push_file, state_deploy
from django.http import JsonResponse
from utils.paginator import my_paginator
from django.db.models import Q
from .models import *
from dataPlus.settings import MEDIA_ROOT
import os
import time
import datetime
from dataPlus.settings import scheduler
from dataPlus.settings import mongo
# Create your views here.

def JobIndex(request):
    return render(request, 'jobs/index.html')

def JobCmd(request):
    if request.method == "POST":
        try:
            user = request.user.username
            if 'HTTP_X_FORWARDED_FOR' in request.META:
                client =  request.META['HTTP_X_FORWARDED_FOR']  
            else:
                client = request.META['REMOTE_ADDR']
            hosts = request.POST.get('hosts', [])
            host_nums = len(hosts.split(','))
            command = request.POST.get('command', '')
            ret, error = Cmd(user, client, hosts, command)
        except Exception as e:
            error = str(e)
    return render(request, 'cmd/index.html', locals())

def UploadFile(request):
    ''' Upload file to remote salt-master server '''
    if request.method == "POST":
        try:
            file = request.FILES.get("file", None)
            file_type = request.POST.get('file_type', '')
            user = request.user.username
            if 'HTTP_X_FORWARDED_FOR' in request.META:
                client =  request.META['HTTP_X_FORWARDED_FOR']
            else:
                client = request.META['REMOTE_ADDR']
            if file_type == 'other':
                myfile, updated = File.objects.update_or_create(code=file.name, name=file.name, defaults={'created_by':user})
                res = upload_file(file, os.path.join(MEDIA_ROOT, 'files'))
            elif file_type == 'script':
                myfile, updated = File.objects.update_or_create(code=file.name, name=file.name, \
                    file_type='script', defaults={'created_by':user})
                res = upload_file(file, os.path.join(MEDIA_ROOT, 'scripts'))
            else:
                myfile, updated = File.objects.update_or_create(code=file.name, name=file.name, \
                    file_type='state', defaults={'created_by':user})
                res = upload_file(file, os.path.join(MEDIA_ROOT, 'states'))
            if res:
                myfile.delete()
                res = {'code': 0, 'msg': res}
            else:
                res = {'code': 1, 'msg': '文件上传成功', 'filename': file.name }
        except Exception as e:
            res = {'code': 0, 'msg': str(e)}
    return JsonResponse(res)

def ViewFile(request, id):
    try:
        script = File.objects.get(pk=id)
        file = os.path.join(MEDIA_ROOT, 'scripts', script.code)
        f = open(file,'r')
        context = f.read()
        f.close()
    except Exception as e:
        context = str(e)
    return render(request,'scripts/context.html',locals())

def DeleteFile(request, id):
    ''' Delete file '''
    try:
        File.objects.filter(pk=id).delete()
        res = {'code': 1, 'msg': '删除成功 ！'}
    except Exception as e:
        res = {'code': 0, 'msg': str(e)}
    return JsonResponse(res)

def ScriptIndex(request):
    return render(request, 'scripts/index.html')

def ScriptListAPI(request):
    ''' script list  API'''
    keyword = request.GET.get('keyword', '')
    if keyword:
        q = Q(code__icontains=keyword) | Q(name__icontains=keyword)
        scripts = File.objects.filter(file_type='script').filter(q)
    else:
        scripts = File.objects.filter(file_type='script')
    data = [{'id': script.id, 'code': script.code, 'name': script.name, 'file_type': script.file_type, 'created_by': script.created_by, \
    'comment': script.comment, 'create_time': script.create_time.strftime("%Y:%m:%d %H:%M:%S"), 'update_time': script.update_time.strftime("%Y:%m:%d %H:%M:%S")} for script in scripts ]
    page = request.GET.get('page', 1)
    limit = request.GET.get('limit', 10)
    count, data = my_paginator(data, page, limit)

    res = {'code': 0, 'msg': '', 'count': count, 'data': data}
    return JsonResponse(res)

def ScriptRun(request, id):
    script = File.objects.get(pk=id)
    if request.method == "POST":
        try:
            hosts = request.POST.get('hosts')
            host_nums = len(hosts.split(','))
            if 'HTTP_X_FORWARDED_FOR' in request.META:
                client =  request.META['HTTP_X_FORWARDED_FOR']  
            else:
                client = request.META['REMOTE_ADDR']
            user = request.user.username
            ret, error = run_script(user, client, hosts, script.code)
        except Exception as e:
            error = str(e)
    return render(request,'scripts/run.html',locals())

def FileIndex(request):
    return render(request, 'files/index.html')

def FileListAPI(request):
    ''' script list  API'''
    keyword = request.GET.get('keyword', '')
    if keyword:
        q = Q(code__icontains=keyword) | Q(name__icontains=keyword)
        scripts = File.objects.filter(file_type='other').filter(q)
    else:
        scripts = File.objects.filter(file_type='other')
    data = [{'id': script.id, 'code': script.code, 'name': script.name, 'file_type': script.file_type, 'created_by': script.created_by, \
    'comment': script.comment, 'create_time': script.create_time.strftime("%Y:%m:%d %H:%M:%S"), 'update_time': script.update_time.strftime("%Y:%m:%d %H:%M:%S")} for script in scripts ]
    page = request.GET.get('page', 1)
    limit = request.GET.get('limit', 10)
    count, data = my_paginator(data, page, limit)

    res = {'code': 0, 'msg': '', 'count': count, 'data': data}
    return JsonResponse(res)

def FilePush(request, id):
    ''' push file to remote host(s) by saltstack '''
    if request.method == "POST":
        try:
            user = request.user.username
            if 'HTTP_X_FORWARDED_FOR' in request.META:
                client =  request.META['HTTP_X_FORWARDED_FOR']  
            else:
                client = request.META['REMOTE_ADDR']
            hosts = request.POST.get('hosts', '')
            host_nums = len(hosts.split(','))
            filename = request.POST.get('filename', '')
            remote_path = request.POST.get('remote_path', '')
            arg_list = [filename, remote_path, 'makedirs=True']
            ret, error = push_file(user, client, hosts, arg_list)
        except Exception as e:
            error = str(e)
    file = File.objects.get(pk=id)
    return render(request, 'files/push.html', locals())


def StateIndex(request):
    return render(request, 'states/index.html')

def StateListAPI(request):
    ''' script list  API'''
    keyword = request.GET.get('keyword', '')
    if keyword:
        q = Q(code__icontains=keyword) | Q(name__icontains=keyword)
        scripts = File.objects.filter(file_type='state').filter(q)
    else:
        scripts = File.objects.filter(file_type='state')
    data = [{'id': script.id, 'code': script.code, 'name': script.name, 'file_type': script.file_type, 'created_by': script.created_by, \
    'comment': script.comment, 'create_time': script.create_time.strftime("%Y:%m:%d %H:%M:%S"), 'update_time': script.update_time.strftime("%Y:%m:%d %H:%M:%S")} for script in scripts ]
    page = request.GET.get('page', 1)
    limit = request.GET.get('limit', 10)
    count, data = my_paginator(data, page, limit)

    res = {'code': 0, 'msg': '', 'count': count, 'data': data}
    return JsonResponse(res)

def StateDeploy(request, id):
    script = File.objects.get(pk=id)
    if request.method == "POST":
        try:
            hosts = request.POST.get('hosts')
            host_nums = len(hosts.split(','))
            if 'HTTP_X_FORWARDED_FOR' in request.META:
                client =  request.META['HTTP_X_FORWARDED_FOR']  
            else:
                client = request.META['REMOTE_ADDR']
            user = request.user.username
            res, error = state_deploy(user, client, hosts, script.code.split('.')[0])
        except Exception as e:
            error = str(e)
    return render(request,'states/deploy.html',locals())

def CronIndex(request):
    return render(request,'cron/index.html',locals())

def CronListAPI(request):
    job_instances = scheduler.get_jobs()
    data = [{'id':job.id, 'cron_string':job.meta['cron_string'], 'targets':','.join(job.args[2]), \
    'arg':job.args[3], 'created_at':job.created_at.strftime("%Y-%m-%d %H:%M:%S"), \
    'last_exacuted':job.ended_at.strftime("%Y-%m-%d %H:%M:%S") if job.ended_at else ''} for job in job_instances]
    
    page = request.GET.get('page', 1)
    limit = request.GET.get('limit', 10)
    count, data = my_paginator(data, page, limit)
      
    res = {'code': 0, 'msg': '', 'count': count, 'data': data}
    return JsonResponse(res)

def CronAdd(request):
    if request.method == 'POST':
        cron_string = request.POST.get('cron_string', '')
        cron_type = request.POST.get('cron_type', '')
        try:
            user = request.user.username
            if 'HTTP_X_FORWARDED_FOR' in request.META:
                client =  request.META['HTTP_X_FORWARDED_FOR']  
            else:
                client = request.META['REMOTE_ADDR']
            arg_list = request.POST.get('cmd', '') if request.POST.get('cmd', '') else 'echo hello'
            hosts = request.POST.get('hosts', '')
            target = hosts.split(',')
            print(target, hosts)
            if cron_type == 'command':
                job = scheduler.cron(cron_string, func=Cmd, args=[user, client, target, arg_list], repeat=None, queue_name='default')
            else:
                job = scheduler.cron(cron_string, func=run_script, args=[user, client, target, arg_list, True], repeat=None, queue_name='default')
            if job:
                res = {'code': 1, 'msg': '任务创建成功 ！'}
            else:
                res = {'code': 0, 'msg': '任务创建失败 ！'}
        except Exception as e:

code/jobs/templates/states/deploy.html
{% load staticfiles %}
<!DOCTYPE html>
<html style="padding-left: 10px; padding-right: 10px; margin-top: 10px;">
<head>
  <meta charset="utf-8">
  <title>jobs-deploy</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}"  media="all">
</head>
<body>

<div>

	<form class="layui-form" action="{% url 'jobs:StateDeploy' script.id %}" method="post" id="myForm">{% csrf_token %}
	    <div class="layui-form-item">
	        <label class="layui-form-label">模块 <span style="color: #FF5722">*</span></label>
	        <div class="layui-input-block">
	        	<input type="text" name="script" lay-verify="required" placeholder="请输入要执行的模块名" class="layui-input" value="{{script.code}}">
	        </div>
	    </div>

      <div class="layui-input-block" id='host_nums'>
        {% if host_nums %}
          <span style="color: green">已选{{host_nums}}台</span>
        {% else %}
          已选0台
        {% endif %}
      </div>

	    <input type="hidden" name="hosts" id="hosts" placeholder="请输入内容主机salt客户端id, 或者点击下方按钮筛选主机" class="layui-input" value="{{ hosts }}">

	    <div class="layui-form-item">
	        <div class="layui-input-block">
	            <button class="layui-btn" lay-submit="" lay-filter="demo1">立即执行</button>
	            <button class="layui-btn" type="button" onclick="select_host()">添加主机</button>
	        </div>
	    </div>
	</form>
	
    {% if res %}
         {% for minion, return in res.items %}
            <pre class="layui-code" lay-title="{{minion}}" lay-skin="notepad">

                {% for key, value in return.process.items %}
Step {{key}} | {{value.id}}:
{{'Name'|rjust:'15'}}: {{value.name}}
{{'Function'|rjust:'15'}}: {{value.fun}}
{{'Result'|rjust:'15'}}: {{value.result}}
{{'Comment'|rjust:'15'}}: {{value.comment}}
{{'Started'|rjust:'15'}}: {{value.start_time}}
{{'Duration'|rjust:'15'}}: {{value.duration}} ms
{{'Stderr'|rjust:'15'}}: {{value.changes.stderr}}
{{'Stdout'|rjust:'15'}}: 
{{value.changes.stdout}}
                {% endfor %}

Summary:
{{'Succeeded'|rjust:'15'}}: {{return.summary.succeeded}}
{{'Failed'|rjust:'15'}}: {{return.summary.failed}}
{{'Total_Duration'|rjust:'15'}}: {{return.summary.total_duration}} ms
            </pre>
          {% endfor %}
    {% endif %}

    {% if error %}
    <pre class="layui-code" lay-title="error" lay-skin="notepad">
<span style="color: red;">{{error}}</span>
    </pre>   
    {% endif %}
</div>

<script src="{% static 'layui/layui.all.js' %}" charset="utf-8"></script>

<script>
    var $ = layui.$;
    var layer = layui.layer;
    function select_host() {
        layer.open({
            type: 2,
            title: '筛选主机',
            maxmin: true, //开启最大化最小化按钮
            area: ['90%', '90%'],
            content: "{% url 'cmdb:HostSelect' %}"
        });
        return false;
    }

    var form = layui.form;
    form.on('submit(demo1)', function(data){
        // post for update
        var index = layer.load(1);
        document.getElementById("myForm").submit()
        return false;
     });

layui.use('code', function(){ //加载code模块
  layui.code(); //引用code方法
});
</script>
</body>
</html>

code/jobs/templates/states/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html style="padding-left: 10px; padding-right: 10px; margin-top: 10px;">
<head>
  <meta charset="utf-8">
  <title>state-list</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}"  media="all">
</head>
<body>

<div>
	{% csrf_token %}
    <div class="layui-inline">
        <div class="layui-input-inline">
            <input type="text" id="keyword" name="keyword" placeholder="根据模块名搜索" autocomplete="off" class="layui-input" style="width: 320px;">
        </div>
    </div>
    <button type="button" class="layui-btn" id="test1"><i class="layui-icon">&#xe67c;</i>上传模块</button>
    <table class="layui-hide" id="demo" lay-filter="demo"></table>
</div>



<script src="{% static 'layui/layui.all.js' %}" charset="utf-8"></script>
<script type="text/html" id="barDemo">
    <a class="layui-btn layui-btn-xs" lay-event="deploy">部署</a>
    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
</script>

<script>
    var table = layui.table;
    var layer = layui.layer;
    var tableIns = table.render({
        elem: '#demo'
        ,url: '/jobs/states/list/api' //数据接口
        ,cols: [[
        {field: 'code', title: '模块', width:150, fixed: true}
        ,{field: 'created_by', title: '上传用户', width:120} 
        ,{field: 'create_time', title: '创建时间', minWidth: 150}
        ,{field: 'update_time', title: '上次修改时间', minWidth: 150}
        ,{title: '操作', fixed: 'right', width:180, align:'center', toolbar: '#barDemo'}
        ]]
        ,page: true
        ,limits: [10,50,100,1000]
    });

    //监听工具条
    table.on('tool(demo)', function(obj){
        var data = obj.data;
        if (obj.event === 'deploy') {
            window.location.href = '/jobs/state/deploy/' + data.id;
        } else if (obj.event === 'del') {
            layer.confirm('确定删除？', function(index){
                $.get('/jobs/file/delete/' + data.id, function(res){
                    if (res.code) {
                        obj.del();
                        layer.msg(res.msg, {icon: 1});
                    }
                    else {
                        layer.alert('错误信息:'+ res.msg);
                    }
                });
                layer.close(index);
            });
        }
    });

    var $ = layui.$;
    function tableReload() {
        var keyword = $("#keyword").val();
        //console.log(keyword)
        //执行重载
        tableIns.reload({
            url: '/jobs/states/list/api',
            where: {'keyword': keyword}
        });
    }

    $('#keyword').bind('keydown', function(event){
        if (event.keyCode == '13'){
            tableReload();
        }
    });

    var upload = layui.upload;
    //执行实例
    var csrfmiddlewaretoken = $("input[name='csrfmiddlewaretoken']").val();
    var uploadInst = upload.render({
        elem: '#test1' //绑定元素
        ,url: "{% url 'jobs:UploadFile' %}" //上传接口
        ,data: {'csrfmiddlewaretoken': csrfmiddlewaretoken, 'file_type': 'state'}
        ,accept: 'file'
        ,exts: 'tar|tar.gz|sls'
        ,done: function(res, index, upload){
        //上传完毕回调
            if (res.code) {
                layer.msg(res.msg);
                tableReload();
            } else {
                layer.alert(res.msg);
            }
        }
        ,error: function(){
        //请求异常回调
            layer.msg('文件上传失败');
        }
    });
</script>
</body>
</html>