code/admins/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import TemplateView
from . import views

app_name='admins'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/list/', views.MenuList, name='MenuList'),
    path('menu/list/api', views.MenuListAPI, name='MenuListAPI'),
    path('menu/add/', views.MenuAdd, name='MenuAdd'),
    re_path(r'^menu/detail/(?P<id>\d+)/$', views.MenuDetail, name='MenuDetail'),
    re_path(r'^menu/update/(?P<id>\d+)/$', views.MenuUpdate, name='MenuUpdate'),
    re_path(r'^menu/delete/(?P<id>\d+)/$', views.MenuDelete, name='MenuDelete'),
    path('user/list/', views.UserList, name='UserList'),
    path('user/list/api', views.UserListAPI, name='UserListAPI'),
    path('user/add/', views.UserAdd, name='UserAdd'),
    path('user/set/', views.UserSet, name='UserSet'),
    re_path(r'^user/detail/(?P<id>\d+)/$', views.UserDetail, name='UserDetail'),
    re_path(r'^user/profile/(?P<id>\d+)/$', views.UserProfile, name='UserProfile'),
    re_path(r'^user/update/(?P<id>\d+)/$', views.UserUpdate, name='UserUpdate'),
    re_path(r'^user/resetpass/(?P<id>\d+)/$', views.ResetPass, name='ResetPass'),
    re_path(r'^user/delete/(?P<id>\d+)/$', views.UserDelete, name='UserDelete'),
    re_path(r'^user/changepass/(?P<id>\d+)/$', views.ChangePass, name='ChangePass'),
    path('role/list/', views.RoleList, name='RoleList'),
    path('role/add/', views.RoleAdd, name='RoleAdd'),
    re_path(r'^role/update/(?P<id>\d+)/$', views.RoleUpdate, name='RoleUpdate'),
    re_path(r'^role/delete/(?P<id>\d+)/$', views.RoleDelete, name='RoleDelete'),
    path('perm/list/', views.PermList, name='PermList'),
    path('perm/update/', views.PermUpdate, name='PermUpdate'),
    path('service/list/', views.ServiceList, name='ServiceList'),
    re_path(r'^service/update/(?P<id>\d+)/$', views.ServiceUpdate, name='ServiceUpdate'),
]

code/cmdb/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name='cmdb'
urlpatterns = [
    path('host/create_or_update', views.CreateOrUpdateHostAPI, name='CreateOrUpdateHost'),
    path('host/index', views.HostIndex, name='HostIndex'),
    path('host/list', views.HostList, name='HostList'),
    path('host/select', views.HostSelect, name='HostSelect'),
    path('host/list/api', views.HostListAPI, name='HostListAPI'),
    path('host/add', views.HostAdd, name='HostAdd'),
    path('host/model', views.HostModel, name='HostModel'),
    path('host/addprop', views.HostAddProp, name='HostAddProp'),
    path('host/search', views.HostSearch, name='HostSearch'),
    path('host/hostupdatebatch', views.HostUpdateBatch, name='HostUpdateBatch'),
    path('host/hostexport', views.HostExport, name='HostExport'),
    path('host/hostimport', views.HostImport, name='HostImport'),
    re_path(r'^host/detail/(?P<id>\d+)/$', views.HostDetail, name='HostDetail'),
    re_path(r'^host/update/(?P<id>\d+)/$', views.HostUpdate, name='HostUpdate'),
    re_path(r'^host/delete/(?P<id>\d+)/$', views.HostDelete, name='HostDelete'),
    re_path(r'^host/updateprop/(?P<id>\d+)/$', views.HostUpdateProp, name='HostUpdateProp'),
    re_path(r'^host/delprop/(?P<id>\d+)/$', views.HostDelProp, name='HostDelProp'),
]

code/admins/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>DataPlus-admins</title>
  <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
  <link href="{% static 'pics/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />
</head>
<body class="layui-layout-body">
<div class="layui-layout">
    <div class="layui-side layui-bg-black" id="sidebar">
        <div class="layui-side-scroll">
          <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree"  lay-filter="test">
                <li class="layui-nav-item"><a href="{% url 'admins:MenuList' %}" target="iframe">模块管理</a></li>
                <li class="layui-nav-item"><a href="{% url 'admins:UserList' %}" target="iframe">用户管理</a></li>
                <li class="layui-nav-item"><a href="{% url 'admins:RoleList' %}" target="iframe">角色管理</a></li>
                <li class="layui-nav-item"><a href="{% url 'admins:PermList' %}" target="iframe">权限管理</a></li>
                <li class="layui-nav-item"><a href="{% url 'admins:ServiceList' %}" target="iframe">服务管理</a></li>
            </ul>
        </div>
    </div>
    <div class="layui-body">
       <iframe id="iframe" name="iframe" scrolling="yes" onload="changeFrameHeight()" frameborder="0" width="100%" src="{% url 'admins:MenuList' %}"></iframe>
    </div>
</div>
<script src="{% static 'layui/layui.all.js' %}"></script>
<script type="text/javascript">
    function changeFrameHeight(){
        var ifm=document.getElementById("iframe");
            // ifm.height=document.documentElement.clientHeight;
            ifm.height=document.getElementById("sidebar").offsetHeight-3;
      }

    window.onresize=function(){  
       changeFrameHeight();
    } 

</script>
<script>
//JavaScript代码区域
layui.use('element', function(){
  var element = layui.element;
});
</script>
</body>
</html>